### ISSUE TITLE
Section 10.67 Issue with S3 Bucket Deployment

### ISSUE THREAD

**Issue by mike-mlmedia** [alexhddev/CDK-course-resources#5]
Thanks for your excellent course Alex.  

I am running into an issue with Section 10.67 when trying to deploy the DataStack with the S3Bucket Deployment, getting this error:

```
CREATE_FAILED        | AWS::S3::BucketPolicy | SpaceFinderFrontendPolicyFFE9DC58
Resource handler returned message: "Access Denied (Service: S3, Status Code: 403, Request ID: NWD
Z1JT0ZDZ94Y6B, Extended Request ID: dDODqF6VavrYMn2OASDulmlQmFrqIIdpFZJViUANd35RkYr2Mchgl+IPSb5ng
/jgG6eJq+bg390=)" (RequestToken: d970d429-f68f-6c36-f53a-d2c95e6114b4, HandlerErrorCode: AccessDe
nied)


 ❌  DataStack failed: Error: The stack named DataStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Access Denied (Service: S3, Status Code: 403, Request ID: NWDZ1JT0ZDZ94Y6B, Extended Request ID: dDODqF6VavrYMn2OASDulmlQmFrqIIdpFZJViUANd35RkYr2Mchgl+IPSb5ng/jgG6eJq+bg390=)" (RequestToken: d970d429-f68f-6c36-f53a-d2c95e6114b4, HandlerErrorCode: AccessDenied)
    at FullCloudFormationDeployment.monitorDeployment (/usr/local/lib/node_modules/aws-cdk/lib/index.js:421:10708)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/usr/local/lib/node_modules/aws-cdk/lib/index.js:424:180229)
    at async /usr/local/lib/node_modules/aws-cdk/lib/index.js:424:163477

 ❌ Deployment failed: Error: The stack named DataStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Access Denied (Service: S3, Status Code: 403, Request ID: NWDZ1JT0ZDZ94Y6B, Extended Request ID: dDODqF6VavrYMn2OASDulmlQmFrqIIdpFZJViUANd35RkYr2Mchgl+IPSb5ng/jgG6eJq+bg390=)" (RequestToken: d970d429-f68f-6c36-f53a-d2c95e6114b4, HandlerErrorCode: AccessDenied)
    at FullCloudFormationDeployment.monitorDeployment (/usr/local/lib/node_modules/aws-cdk/lib/index.js:421:10708)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/usr/local/lib/node_modules/aws-cdk/lib/index.js:424:180229)
    at async /usr/local/lib/node_modules/aws-cdk/lib/index.js:424:163477

The stack named DataStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Access Denied (Service: S3, Status Code: 403, Request ID: NWDZ1JT0ZDZ94Y6B, Extended Request ID: dDODqF6VavrYMn2OASDulmlQmFrqIIdpFZJViUANd35RkYr2Mchgl+IPSb5ng/jgG6eJq+bg390=)" (RequestToken: d970d429-f68f-6c36-f53a-d2c95e6114b4, HandlerErrorCode: AccessDenied)
```
The code was copied exactly as it was in the repository for `space-finder` and the `space-finder-frontend` directories.  

Wondering if you have any insights on this one.

**Comment by mike-mlmedia** [comment]
Seems as if there's an issue with the "publicReadAccess: true," line in the `DataStack.ts` file.  What would be the best workaround for this?

**Comment by mike-mlmedia** [comment]
After some playing around, I **_manually_** set off the `Block public access (bucket settings)` for the S3 bucket to `Off` and then re-deployed and the `publicReadAccess` setting was fine.  Wondering if there is something to add to the following (from the `DataStack.ts` file to do this automatically through the CDK?

```
this.deploymentBucket = new Bucket(this, "SpaceFinderFrontend", {
	bucketName: `space-finder-frontend-${suffix}`,
	publicReadAccess: true,
	/* NOTE: the above throws an error TODO: find a workaround to make s3 bucket public */
	websiteIndexDocument: "index.html",
});
```

The CDK docs don't seem to help and I can't find anything on-point out in StackOverflow or elsewhere on it.

**Comment by bronifty** [comment]
@mike-mlmedia 

this.deploymentBucket = new Bucket(this, "SpaceFinderFrontend", {
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
      bucketName: `space-finder-frontend-${suffix}`,
      publicReadAccess: true,
      websiteIndexDocument: "index.html",
      blockPublicAccess: {
        blockPublicAcls: true,
        blockPublicPolicy: false,
        ignorePublicAcls: true,
        restrictPublicBuckets: false,
      },
    });
